### ISSUE TITLE
`SAFRasterizerDelegator 🔴` - Parameters: input_layer, output_path | Return Type: Not Specified

### ISSUE THREAD

**Issue by timlinux** [kartoza/GEEST2#12]

**Comment by osundwajeff** [comment]
`def SAFRasterizerDelegator(self)`

Used in: 

- `SAFnightTimeLights` for raster inputs.
- `SAFstreetLightsRasterizer` for vector point inputs.
- `SAFPerceivedSafetyFromNumericFieldRasterizer`
- `SAFPerceivedSafetyFromTextFieldRasterizer` for polygon vector inputs based on the field type.
