### ISSUE TITLE
Implement CSV to Point Layer functionality

### ISSUE THREAD

**Issue by timlinux** [kartoza/GEEST2#15]
We need to create a raster with cell values from 0-5, where the cells that intersect any of the buffers from the events, take the score as per the table below. If a cell intersect more types of events, it will take the score of the more serious event, as in the classification below.

5km buffer from event points

• Raster cells overlapping with buffers indicating battles and explosions: score 0
• Raster cells overlapping with buffers indicating explosions and remote violence: score 1
• Raster cells overlapping with buffers indicating violence against civilians: score 2
• Raster cells overlapping with buffers indicating protests and riots: score 4
• Raster cells that do not overlap with any event: score 5

Please let me know if everything is clear, or you have more questions - thanks!

The CSV files can be found here:
https://drive.google.com/drive/folders/1e5RjSZdRBaY7i7YDX9aQZaqVTvY6JRRT

**Comment by osundwajeff** [comment]
`def populateCBFieldsFromPolygonLayer_PC_ENV(self, file_path)`

Currently not used. Should be removed.

**Comment by timlinux** [comment]
"Use CSV to Point Layer" is the layer key
