### ISSUE TITLE
Implement Classified Polygon functionality

### ISSUE THREAD

**Issue by timlinux** [kartoza/GEEST2#18]
We need a function that classifies polygons into a scale of 0 to 5 based on their attributes.
The processor uses the value_field (e.g., safety) from the safety_layer to assign values.

#### **Signature:**

```python
SafetyPerCellProcessor(output_prefix, safety_layer, workflow_directory, gpkg_path)
```

## Inputs:
`output_prefix: str` — A prefix for naming the output files.
`safety_layer: QgsVectorLayer` — The input vector layer containing polygons with the safety attribute.
`workflow_directory: str` — The directory where output files will be saved.
`gpkg_path: str` — The path to the GeoPackage containing the study areas (study_area_grid layer).

## Outputs:
QgsRasterLayer
The analysis will generate a new raster layer in the input CRS and dimensions of the input bbox and cell size. It will be assigned a value between 0 and 5. All values outside of the country_boundary will be assigned as no data values.

## Testing:
Prepare a small sample dataset for the boundary and verify that the classification generates correctly

**Comment by osundwajeff** [comment]
There's a version 2 of this function #19 . that should be adopted.
