### ISSUE TITLE
Implement the mulibuffer point layer generator widget

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST2#262]
We need a widget that contains these elements:

- [ ] A text description explaining the input data.
- [ ]  A QgsMapLayerComboBox to select the point layer
- [ ] A radio button that has the Travel Mode. Walking should be selected as a default
- [ ] A radio button that has the Measurement. Distance should be selected as a default
- [ ] A text box to enter the buffer increments. The default should be 250, 500, 750, 1000, 1250

![image](https://github.com/user-attachments/assets/2fcad676-d538-40d9-a47f-24e3326e03cd)

## Input:

* "Default Multi Buffer Distances": "250, 500, 750, 1000, 1250", 
* "Default Multi Buffer Travel Mode": "Walking" (with Walking, Driving being valid options)
* "Default Multi Buffer Measurement": "Distance" (with Distance, Time being valid options)

This should be used to define the initial distances

## Output:

A dictionary of item values for the Layer Node. From this dictionary the following elements should be populated by this widget:

* "Multi Buffer Distances": "0,0,0",
* "Multi Buffer Travel Mode": "Walking" (with Walking, Driving being valid options)
* "Multi Buffer Measurement": "Distance" (with Distance, Time being valid options)

These entries should be appended to or overwrite entries with the same name as provided in the input dictionary.

See also #261  for the backend function

**Comment by hennie-k** [comment]
The **"Multi Buffer Travel Mode"** and **"Multi Buffer Measurement"** inputs are not currently included in the input dict and needs to be included for this widget to be completed

**Comment by hennie-k** [comment]
Workaround: the widget emits (for example) `...,'Use Multi Buffer Point': 'Driving;Distance;250, 500, 750, 1000, 1250',...`
