### ISSUE TITLE
Implement the aggregate layer generator widget

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST2#266]
We need a widget that contains these elements:

A text description explaining the input data.

Layer input boxes

Spin boxes for the weighting

![image](https://github.com/user-attachments/assets/c05fe480-a210-44b2-986f-b9e66aade885)

See also #265  for the back-end function

**Comment by mvmaltitz** [comment]
Edit weighting in the weight column instead

![Image](https://github.com/user-attachments/assets/31e32e2f-f3df-4d6f-b3d8-23fbb963b425)

**Comment by hennie-k** [comment]
This ticket contains conflicting/unclear instructions. The title and description calls for an "aggregate layer generator widget" but is superseded by the comment that it should "edit weighting in the weight column instead". The code that generates/manages the tree view (of which I am not the author) is not fully operational yet and causes errors when interacted with, which prevents implementation of the requirement of this ticket.

![Image](https://github.com/user-attachments/assets/2d27822f-566d-4821-9f67-10fb28811546)

**Comment by hennie-k** [comment]
There are 2 layers of weightings:
![Image](https://github.com/user-attachments/assets/a8ec2462-aace-4791-b028-27422d91a502)

**Comment by mvmaltitz** [comment]
Close issue as we are not going to have a widget for this, it will be considered in the weight column 
![Image](https://github.com/user-attachments/assets/74b3e8a1-677c-4174-a295-c61726743d2a)
