### ISSUE TITLE
Develop Standardized Cartography for Vector and Raster Representations of Indicators

### ISSUE THREAD

**Issue by timlinux** [kartoza/GEEST2#313]
This task involves developing standardized cartographic rules for visualizing each indicator, depending on whether the data is represented as vectors or rasters. The process includes:
1. **Standardized Vector Cartography**: Define visual styles for vector data representations of indicators.
2. **Standardized Raster Cartography**: Develop styling rules for raster data, such as color ramps and classifications.
3. **Automatic Application**: Implement a system to automatically apply the correct cartography based on the data type (vector or raster).
4. **Customization for Specific Indicators**: Allow for slight customizations in cartography for specific indicators when necessary.

**Comment by mvmaltitz** [comment]
@osundwajeff 

Here are the cartography for the different factors:

### Contextual
![Image](https://github.com/user-attachments/assets/b87dd2eb-a897-4f78-a832-3412d150d68c)

### Accessibility
![Image](https://github.com/user-attachments/assets/1d39e4c4-7645-41aa-a786-89a567472b0d)
![Image](https://github.com/user-attachments/assets/51caf328-7c01-4454-ad4c-5d37521359c6)

### Place Characterization
![Image](https://github.com/user-attachments/assets/30524315-37fd-45ac-ab2e-ba3d13d4890c)
![Image](https://github.com/user-attachments/assets/2bf218ac-219b-4a91-9a05-c109640096f6)
