### ISSUE TITLE
Delete Weights Column

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/GEEST2#370]
Please delete the Weights column from the Inputs tab -this should be an option inside the Properties Tab for each dimension/factor -> all the values are default but users should have the option to adjust.

![Image](https://github.com/user-attachments/assets/bf53bf8c-85f2-4c15-89b5-dca8b10b3b08)

![Image](https://github.com/user-attachments/assets/04e9c4f8-97fe-4d92-9840-ffb5e7558067)

**Comment by timlinux** [comment]
Will do thanks.
