### ISSUE TITLE
<Run> option for each factor/ dimension

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/GEEST2#371]
We would like to have a "run" button next to each dimension and each factor, as well as to keep the RUN ALL option. 

This will give more flexibility to users if they want to re-do an analysis with better data, or are only interested in one factor at a time.

![Image](https://github.com/user-attachments/assets/810a9c36-2bb0-45b1-99fe-a697a1c5f315)

**Comment by timlinux** [comment]
This is implemented in the next dev release (see https://github.com/kartoza/GEEST2/releases). We will make the release on Tuesday, probably with other feature improvements too.

Note that it is implemented by right clicking an item to run it.

[Screencast from 2024-10-06 21-37-16.webm](https://github.com/user-attachments/assets/b8149dc0-91cd-49a3-b89c-f9bbc2e190a1)
