### ISSUE TITLE
Format the Inputs List as a tree

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/GEEST2#372]
Grateful if you could make the tree structure be more evident, by making in Bold the dimensions, factors and layers – similar to headers H1, H2 and H3 -> this will make it easier for users to navigate all the data layers. 

![Image](https://github.com/user-attachments/assets/940b4cf8-3531-41ef-aaa7-a1ea619f57ec)

**Comment by timlinux** [comment]
Yes great, I will do that. I was thinking to make little icons to put in front of each concept (Dimension, Factor, Indicator) too

**Comment by timlinux** [comment]
Something like this @ClaraIV 

![image](https://github.com/user-attachments/assets/e500460e-3bcc-4008-abaa-7ae396830008)


I am still going to make the status column look pretty too...
