### ISSUE TITLE
Pop-up box on Plugin Initiation (start fresh or continue project)

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/GEEST2#377]
After setting the directory, whenever we close and open it again, the last Working Directory has been set, this is inline with what Tim explain about setting in JSON file.
We think it would be good if we have a "Reset" option on this page. The function is to make everything like a fresh start and to prevent users from using unwanted folders.

**We suggest a dialog box to open upon tool initiation that asks the user if he wants to continue with the previous project or to clean it up and start a new one.**

**Comment by timlinux** [comment]
Hi @ClaraIV . Usually it is better not to have any pop up dialogs when a plugin starts as they block the user interface until the user interacts with it. I propose that I rather add some options in the dock like:

* Continue your last session in folder XXX/YYY/ZZZ
* Start a new session by selecting an empty working folder
* Select a previous session from another working folder

**Comment by ClaraIV** [comment]
this looks very nice! thanks!

**Comment by timlinux** [comment]
@ClaraIV just to wrap up this ticket for now I have made this:

**Comment by ClaraIV** [comment]
hi Tim, we still need the option for the user to upload a file (browse to a location and select a file), even on the homepage - it's not clear that the users should first load all of their data in QGIS and it will also be very practical to have this option everywhere @timlinux
