### ISSUE TITLE
Add "Processing.." or Progress Bar on 1st step

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/GEEST2#378]
After setting the working directory, add the boundary set the Study Area Layer and Area Name Field, follow with click Continue button. I understand the process is starting, when I checked the working directory folder, it generates GeoTIFFs and append into GPKG.
But it is not clear from the interface that anything is happening in the background, it seems unresponsive. Could we add  a progress bar or running text to show the process?
We know the progress is available in Log Messages, but it's not intuitive for regular users, and usually they never open this window.

**Comment by timlinux** [comment]
Yes will do. I aim to run this in a background thread once we have confirmed the workflow. I'll add a progress indicator too.
