### ISSUE TITLE
Could not find World Map

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/GEEST2#379]
All the testing encountered issues with using the World Map, we might consider removing this option altogether if its only available for some versions of QGIS or if it's prone to cause errors to the majority of users, grateful if we could touch base on this topic in the next meeting.

![Image](https://github.com/user-attachments/assets/d8573bb5-dc13-44b3-826c-333a03791306)

**Comment by timlinux** [comment]
Thanks @ClaraIV  - let me get @osundwajeff to check on his windows machine. It should be a quick fix, if not we can remove this option.
