### ISSUE TITLE
Handle case when indicator is linked to a layer not loaded in the project

### ISSUE THREAD

**Issue by timlinux** [kartoza/GEEST2#410]
In the widgets for selecting layers we can use QgsMapLayer (nice!) but if you open the project later and that QGIS layer is not there, the indicator should still work. The widget should write the layer path and restore it if the file does not exist in the project.

**Comment by mvmaltitz** [comment]
@osundwajeff Verify that this has been fixed

**Comment by osundwajeff** [comment]
@mvmaltitz Tested all workflows. All good.
