### ISSUE TITLE
Testing Environmental Hazard

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST2#464]
## Input
Raster Layer 
![Image](https://github.com/user-attachments/assets/4ba9aeab-53dd-4a60-9d2b-34036da21eae)

## Layers
1. Forest Fire
2. Flood
3. Landslide
4. Tropical Cyclone
5. Drought

## Output Matrix
Input value range: 0 to x

Input Value | Output Value
-- | --
Outside AOI | No Data
0 | 0
upper value: (x+1)/100*20 | 1
upper value: (x+1)/100*40 |2
upper value: (x+1)/100*60 |3
upper value: (x+1)/100*80 | 4
upper value: x+1| 5 (default value)

The aggregate of all the different layers is calculated for a final output

## Example
![Image](https://github.com/user-attachments/assets/66e21ab4-5cb3-4186-b78d-456456fafd9e)
![Image](https://github.com/user-attachments/assets/5bbf714f-1323-42bb-a244-62c95ec11cdc)

**Comment by mvmaltitz** [comment]
@timlinux @osundwajeff Please can you check my logic for the matrix above

**Comment by mvmaltitz** [comment]
### Testing v0.2.4
## Results
https://github.com/user-attachments/assets/024e27f1-5b3d-4e47-898e-5ebd19493c56

## Expectation
@osundwajeff please check the scores - It looks like they have been reversed with landslide. 
![Image](https://github.com/user-attachments/assets/0d708857-128b-4aa7-8e2b-b4e17be84b28)

**Comment by osundwajeff** [comment]
On this I am able to replicate it:

![Image](https://github.com/user-attachments/assets/71c9fb79-3da5-447a-bf32-dd67eee45508)

Seems the raster is not being reclassified at all.
