### ISSUE TITLE
Check ORS reproject to lat/long

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST2#518]
When it failed (locations):

![Image](https://github.com/user-attachments/assets/136eec9f-03d0-4f1b-873b-ba51298763a6)

When it passes (locations):

![Image](https://github.com/user-attachments/assets/7b373c81-1673-4e14-8227-311d06eb299e)

**Comment by timlinux** [comment]
![Image](https://github.com/user-attachments/assets/9c80a0a9-6d3c-4809-b422-8605047030df)

I tested in Cabo Verde with some reprojected points and they worked fine too...
