### ISSUE TITLE
Check the spreadsheet

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST2#525]
Check that the widgets on the spreadsheet are correctly assigned to the layers/factors

**Comment by mvmaltitz** [comment]
@timlinux @osundwajeff 
I will check that the correct widgets are showing during the testing.

**Comment by osundwajeff** [comment]
# Accessibility:

Default Multi Buffer distances:

WTP: [`400, 800, 1200, 1500, 2000`]

Public transport: [`250, 500, 750, 1000, 1250`]

Education and Training: [`2000, 4000, 6000, 8000, 10000`]

Health facilities: [`2000, 4000, 6000, 8000, 10000`]

Finance facilities: [`400, 800, 1200, 2000, 3000`]

**Comment by osundwajeff** [comment]
# Place characterization

## Active transport: 

- Safety: Still shows one widget when opening for the first time
![Image](https://github.com/user-attachments/assets/dc2ccd6e-bb07-467f-b33c-bb1455e3b274)

After selecting one of the available widgets, then closing dialogue and re-opening, the other widgets then appear:
![Image](https://github.com/user-attachments/assets/ae92e03d-8fc6-4f5f-ae0b-3690bae7c9ff)

But so far the correct widgets appear.

**Comment by osundwajeff** [comment]
## Digital Inclusion:

Use poly per cell widget not required here:

![Image](https://github.com/user-attachments/assets/f989af85-3796-4870-ab51-ab0f772a0337)

**Comment by osundwajeff** [comment]
## Water and Sanitation:

Use multi buffer widget:

![Image](https://github.com/user-attachments/assets/57c85bca-189b-4009-851b-3a14725e64a0)
