### ISSUE TITLE
Combine Kindergartens and primary schools

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST2#529]
Location of kindergardens andprimary schools should be combined in woman travel patterns:
Previous Geest:
![Image](https://github.com/user-attachments/assets/2ba03e01-3101-482e-8857-09040274cd73)

Currently:
![Image](https://github.com/user-attachments/assets/79d141b8-848a-4191-895f-db4e52bf8678)

**Comment by timlinux** [comment]
On the sheet they are separate. Lets confirm with @ClaraIV and update the sheet if needed.

**Comment by ClaraIV** [comment]
indeed, they should be combined. Sorry for the confusion!

**Comment by mvmaltitz** [comment]
As per our meeting on 20 Nov, we will keep these separate
