### ISSUE TITLE
Regulatory Framework change text

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST2#530]
1. Pay and Parenthood (Regulatory Framework) to have 2 options for index score where the weighting is taken between them
![Image](https://github.com/user-attachments/assets/617d0044-ca49-4a7f-91ee-4d5b28a22f90)

**Comment by timlinux** [comment]
Lets ask @ClaraIV if we can combine these so it works the same way as the other index scores rather. Otherwise we need to make a new workflow widget and add a column to the sheet with the needed defaults etc.

**Comment by mvmaltitz** [comment]
Add text to say that the average can be entered (text to be supplied)

**Comment by ClaraIV** [comment]
I think that could work. Let's name the field: **Average** value of **WBL Pay Score** and **Parenthood Index Score**

**Comment by mvmaltitz** [comment]
@timlinux 
![Image](https://github.com/user-attachments/assets/bfe219fe-c56e-46d1-bee6-27520615fe69)

Average value of WBL Pay Score and Parenthood Index Score

**Comment by timlinux** [comment]
![Image](https://github.com/user-attachments/assets/de82c186-671e-4035-a77b-0406c7718e83)
