### ISSUE TITLE
Failed workflow marked as complete

### ISSUE THREAD

**Issue by osundwajeff** [kartoza/GEEST2#536]
During process: #494 

Workflow failed during the initial stages still marked as complete:

![image](https://github.com/user-attachments/assets/6e684582-58b9-4e9b-aca6-e5750cb39fd3)

The process failed during querying of the ORS api, so no isochrones were created.

![image](https://github.com/user-attachments/assets/74e80628-adf5-4b49-8372-d3f02a3cf4f9)

**Comment by timlinux** [comment]
Works for me now @mvmaltitz 

![Image](https://github.com/user-attachments/assets/2b7b15fa-ed46-482b-b9a7-4d04bad56072)


I tested with my network disabled and got an error after it timed out. Then I tested with the network enabled and it runs successfully:

![Image](https://github.com/user-attachments/assets/96c74df1-b4ea-4e35-a6ab-f999f34a93ba)
