### ISSUE TITLE
Fix FCV Widgets

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST2#567]
The Use single buffer point should be using the csv as an input layer (use csv to point layer). 
![Image](https://github.com/user-attachments/assets/75d9dae5-7e94-476d-a42d-295ff1472ef3)

Maybe we could leave the last widget with an editable buffer distance which is auto populated with the default distance?
![Image](https://github.com/user-attachments/assets/404e4e1e-ce04-45d5-bf6e-1d98077d4623)

**Comment by timlinux** [comment]
The single buffer point should also use CSV? Is that right? Will need to write a workflow for that...

**Comment by mvmaltitz** [comment]
@timlinux Yes, There is a default value but you also have an option to change the impact radius (buffer distance)

**Comment by timlinux** [comment]
Based on our discussion today:

Keep the point shapefile processor but make sure the selector is using point geom

![Image](https://github.com/user-attachments/assets/26d5834d-871f-431b-b5da-dcf01d4f2ce9)


In the case of the CSV file, user should have a file chooser widget and then a distance spin (which applies to all indicators)

![Image](https://github.com/user-attachments/assets/f1908156-87e1-41fd-aff6-83afb369631c)
