### ISSUE TITLE
Fix WTP Aggregation

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST2#570]
The WTP aggregation isn't correct
The area pointed out should be 5
![Image](https://github.com/user-attachments/assets/f611933c-e4da-4a29-a0df-e7defcb2d2db)

**Comment by timlinux** [comment]
Will need to investigate this first, size is provisional

**Comment by timlinux** [comment]
![Image](https://github.com/user-attachments/assets/5bc10ca0-6ab4-4bd5-9bd6-4cf56a3466f8)

I believe it is aggregating correctly now.  I dont get exactly the same results as yours but that could depend on weightings and buffer sizes used:

![Image](https://github.com/user-attachments/assets/dc147e44-b84e-46f7-9099-62eced2b47b1)
