### ISSUE TITLE
Fix Nighttime lights

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST2#571]
The score is not correct
![Image](https://github.com/user-attachments/assets/db023378-f05d-428e-b986-72812c66eee1)

There is no "2"
![Image](https://github.com/user-attachments/assets/a2d41a3e-6bb7-4395-aa3d-80dd3a7284ec)

**Comment by timlinux** [comment]
Already fixed in my branch for #434

**Comment by timlinux** [comment]
Maybe needs some more investigation - I still cant replicate the output you got

**Comment by mvmaltitz** [comment]
@timlinux I still get the same result.
