### ISSUE TITLE
Fix environmental hazard aggregation

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST2#572]
The environmental aggregation is not showing correctly

previously vs now:
![Image](https://github.com/user-attachments/assets/06ac0b7a-6bdd-4ffa-9af7-989ce5a9c9f4)

**Comment by timlinux** [comment]
I think switching to float will fix it...

**Comment by timlinux** [comment]
Works for me now @mvmaltitz 

![Image](https://github.com/user-attachments/assets/e6111e0c-b1ba-4c7a-a592-89ad3e13f59b)
