### ISSUE TITLE
Implement rasterize dataset functionality

### ISSUE THREAD

**Issue by timlinux** [kartoza/GEEST2#6]
To describe what the RasterizeSet function does, I'll need to make an educated guess based on the name of the function and the typical operations associated with rasterization in the context of geographic information systems (GIS).

## Likely Purpose of RasterizeSet
The RasterizeSet function most likely converts a set of vector data (e.g., layers, polygons, lines, or points) into raster data. Rasterization is a process where vector data (which is defined by geometric shapes) is converted into a grid of pixels or cells (raster format). Each pixel in the resulting raster can hold a value, such as an attribute of the vector data (e.g., elevation, land cover type).

## Parameters (Based on the Signature):
* layers: This likely represents the vector data layers that you want to rasterize. These could be a list or collection of layers that contain various geographic features.
* attributes: This parameter probably refers to the specific attributes or fields from the vector data that you want to use to assign values to the raster cells.
* raster_size: This could define the resolution or dimensions of the output raster. For example, it might specify the number of rows and columns in the resulting raster grid or the cell size.
## What It Likely Does:
* Input Handling: It takes in a set of vector layers and associated attributes that you want to rasterize.
* Rasterization Process: The function processes each vector layer, converting the geometric features into raster cells. The attribute values from the vector data are then assigned to the corresponding cells in the raster.
* Output Generation: Finally, it outputs a raster dataset that represents the rasterized version of the input vector data.
## Use Case:
* GIS Analysis: The RasterizeSet function would be useful in GIS analysis where raster data is needed for operations like spatial modeling, overlay analysis, or when combining different data layers into a uniform raster format.
If you need a precise description of what RasterizeSet does, I can look deeper into the actual code logic if you'd like!

## Outcome:

Method signature:

rasterize_layer(QgsVectorLayer)

Returns:

QgsRasterLayer

## Validation data:

[Daycare_elementary_schools.zip](https://github.com/user-attachments/files/16849358/Daycare_elementary_schools.zip)

## Testing

Testing should try the function with each of the supported input types and compare with an expected output.

**Comment by osundwajeff** [comment]
`def RasterizeSet(self, factor_no):`

Discontinue use. Currently used in Digital Inclusion `set` button.

**Comment by mvmaltitz** [comment]
- [ ] Rasterize point functionality
- [ ] Rasterize line functionality
- [ ] Rasterize polygon functionality
