### ISSUE TITLE
Weights won't allow for decimal points

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST2#633]
Unable to type in a weighting score with a decimal point
![Image](https://github.com/user-attachments/assets/ace96bf7-7ab0-43c3-8a09-c5b393e982cc)

**Comment by timlinux** [comment]
In addition we should have a 'don't' use option so that the weight can be zero and the calcs get spread across the remaining items.

**Comment by mvmaltitz** [comment]
![Image](https://github.com/user-attachments/assets/8f49b7a6-5508-44df-b0ad-5e73cbf8db35)
