### ISSUE TITLE
v.3.8.: user input triggers python error

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/GEEST2#687]
Be it weights, or values for the indicators, any input I try to add generates this python error

![image](https://github.com/user-attachments/assets/dd16e6fa-a88b-4fb5-a442-4b349fe8dafa)

**Comment by ClaraIV** [comment]
I mention that I uninstalled and reinstalled the latest version, and that I started a fresh project folder, as I am aware of the change in the json model structure.

**Comment by timlinux** [comment]
Thanks for sharing the report - I believe this is already fixed in the current version that will be in the next package we make.
