### ISSUE TITLE
v.3.8 no indicator is being processed

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/GEEST2#688]
set-up in place but no indicator is being processed.

![image](https://github.com/user-attachments/assets/c19c9c0c-c514-44e7-ae14-055fd60a0d0f)

![image](https://github.com/user-attachments/assets/d4286519-dbec-45e3-af83-35c1dce0996e)

**Comment by timlinux** [comment]
@ClaraIV thank you for sharing this. We saw the same error occurring sometimes - it seems like something disables processing support in QGIS. Could you tell me if you also used the old geest on this computer?

There is a trivial fix for the issue but it is manual so let me try to automate it....

**Comment by timlinux** [comment]
@ClaraIV can you please check this is enabled in your plugin manager:

![image](https://github.com/user-attachments/assets/c0c17089-5b25-47cb-9a4f-0a0468c93393)

**Comment by ClaraIV** [comment]
hi @timlinux indeed the "Processing" was not enabled. I enabled it and re-ran the Contextual without success, the status is still "configured but not run". 
I disabled the plugin, closed QGIS. Re-opened QGIS, enabled plugin, checked for the "Processing" option to be enabled and tried again, without success.

![image](https://github.com/user-attachments/assets/37902959-7251-49e3-986b-326a415ff498)

**Comment by timlinux** [comment]
@ClaraIV Can you start a fresh project please - the clip area polygons layer (which is created during project setup) is missing, apologies I should have mentioned that it requires recreating projects after I set that up.
